  - name: Install pacman util packages
    block:
    - name: Install pacman util packages
      tags:
        - godot
      community.general.pacman:
        name: 
          - godot
        state: present

    - name: Install pacman util packages
      community.general.pacman:
        name: vulkan-intel
        tags:
          - godot
          - intel-gpu
        state: present
