  - name: Install godot
    block:
    - name: Install godot
      tags:
        - godot
      community.general.pacman:
        name: 
          - godot
        state: present

    - name: Install godot vulkan-intel support
      community.general.pacman:
        name: vulkan-intel
        state: present
      tags:
        - godot
        - intel-gpu
