
- name: Install graphics drivers
  block:
  - name: Install nvidia
    tags:
      - nvidia
      - workstation
    community.general.pacman:
      name: 
        - nvidia
        - nvidia-settings
      state: latest
