
- name: Install graphics drivers
  block:
  - name: Install nvidia
    tags:
      - nvidia
    community.general.pacman:
      name: 
        - nvidia
        - nvidia-settings
      state: latest
  - name: Install nvidia
    tags:
      - nvidia-legacy
    kewlfft.aur.aur:
      use: yay
      name:
        - nvidia-580xx-dkms
    become: true
    become_user: aur_builder
  - name: Install nvidia
    tags:
      - nvidia
      - nvidia-legacy
    community.general.pacman:
      name: 
        - nvidia-settings
      state: latest
