- block: 
  - name: Install pacman util packages
    community.general.pacman:
      name: 
        - less
      state: present

  - name: Install aur utils
    kewlfft.aur.aur:
      use: yay
      name:
        - ripgrep
    become: true
    become_user: aur_builder

  - name: Install tmuxinator
    kewlfft.aur.aur:
      use: yay
      name:
        - tmuxinator
    become: true
    become_user: aur_builder
