- block: 
  - name: Install reflector
    community.general.pacman:
      name: 
        - reflector
      state: present

  - name: Enable reflector.service
    ansible.builtin.systemd_service:
      name: reflector.service
      state: started
      enabled: true

  - name: Add refelector.conf file
    ansible.builtin.template:
      src: tasks/reflector/reflector.conf
      dest: /etc/xdg/reflector/reflector.conf

  - name: Enable reflector.timer
    ansible.builtin.systemd_service:
      name: reflector.timer
      state: started
      enabled: true


