- block: 
  - name: Install streamlink and vlc
    community.general.pacman:
      name: 
        - streamlink
        # - vlc
        # - vlc-plugin-ffmpeg
        # - libvdpau
        - mpv
      state: latest

  - name: Install chatterino
    community.general.pacman:
      name: chatterino2-bin
      state: latest
    become: true
    become_user: aur_builder

  - name: Update config files
    block:
    - name: Add streamlink config file
      ansible.builtin.template:
        src: tasks/twitch-stuff/streamlink/config
        dest: $HOME/.config/streamlink/config
    become: true
    become_user: "{{ user }}"
